name: laravel_flutter_pusher
description: Pusher client that supports laravel echo in flutter projects. Supports Null satefy
version: 0.0.5
homepage: 'https://github.com/olubunmitosin'

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  json_serializable: ^4.1.0
  build_runner: ^1.12.2


# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.github.olubunmitosin.laravel_flutter_pusher
        pluginClass: LaravelFlutterPusherPlugin
      ios:
        pluginClass: LaravelFlutterPusherPlugin
